Change withComponent yml example to .ts to .tsx
  ✖ ./src/generated/graphql.ts
    Plugin "typescript-react-apollo" requires extension to be ".tsx" when withComponent: true is set!
    Error: Plugin "typescript-react-apollo" validation failed:

Got this error saw a minor error in the example, let me know if theres any issues 🤷‍♂️